plugins {
    id 'dev.architectury.loom' version '1.10-SNAPSHOT'
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

group = project.maven_group
version = project.minecraft_version + "-" + project.mod_version

configurations {
    shadow
    implementation.extendsFrom(shadow)
}

base {
    archivesName = project.archives_name
}

loom {
    silentMojangMappingsLicense()

    forge {
        mixinConfig 'rage.mixins.json'
    }
}

repositories {
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:$project.minecraft_version"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.parchment_version}@zip")
    }
    forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
    shadow(annotationProcessor("io.github.llamalad7:mixinextras-common:${project.mixinextras_version}"))
}

shadowJar {
    configurations = [project.configurations.shadow]
    relocate "com.llamalad7.mixinextras", "me.kall.rage.mixinextras"
    mergeServiceFiles()

    archiveClassifier = "dev-shadow"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

java {
    if (version.startsWith("1.16.5")) {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    } else {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

remapJar {
    dependsOn shadowJar
    inputFile = shadowJar.archiveFile
    archiveClassifier = null
}

tasks.withType(JavaCompile).configureEach {
    if (version.startsWith("1.16.5")) {
        it.options.release = 8
    } else {
        it.options.release = 17
    }
}