org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false


minecraft_version=1.18.2
minecraft_version_range=[1.18.2]

forge_version=40.3.10
forge_version_range=[40,)
loader_version_range=[40,)

mapping_channel=parchment
mapping_version=2022.11.06-1.18.2

mod_id=rage
mod_name=Rage
mod_license=MIT
mod_version=1.18.2-1.0.0
mod_group_id=me.kall.rage
mod_authors=Kasualix
mod_description=A Minecraft mod

# Proxy
# REMOVE THIS IF YOU WANT TO BUILD THIS PROJECT BY YOURSELF
systemProp.http.proxyHost=localhost
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=7890
