org.gradle.jvmargs = -Xmx8192m -XX:MaxMetaspaceSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel = true
org.gradle.caching = true

loom.platform = forge

mod_version = 1.1.1
maven_group = me.kall.rage
archives_name = rage

minecraft_version = 1.18.2
mixinextras_version = 0.5.0

cf_project_id=981032

use_shadow=true
use_mixin=true

use_mixin_extras=true
use_jsonate=false
use_provider=false
use_block_tracker=false
claim_integration=false
embeddium_integration=false
